services:
  - type: web
    name: edumis
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: EDUMIS_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
